### ISSUE TITLE
Comparison vs. Assigment

### ISSUE THREAD

**Issue by daberlin-sechub** [reprise99/Sentinel-Queries#16]
Hi.
File: "Data Management/Data-CalculatePercentageperTable.kql
Code:
    Usage
    | where TimeGenerated > ago(30d)
    | where IsBillable = true
    ...
Correction:
    | where IsBillable == true

Best regards.

**Comment by reprise99** [comment]
Hi there! The top one should also work because the 'IsBillable' field is a boolean, so accepts = true or false, but you can also do it your way and treat it as a string with == "true" or "false"

**Comment by daberlin-sechub** [comment]
Excuse me, but no.
Try adding "IsBillable" to the output and you'll see that "=" is not a comparison operator.

![grafik](https://user-images.githubusercontent.com/101503786/199936575-33ec02b4-5d6f-46ea-8b40-ce049e2d5d1c.png)

**Comment by reprise99** [comment]
Yeah you are right, my bad! Weird that it shows in the schema like that, I will update the query, most appreciated!
