### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by meniqq** [reprise99/Sentinel-Queries#17]
Have a question, need to query : 
User@domain.com added users to groups in AAD between ( some days )
* what are the users name
* to which group he added them

View the information In the following table:
Result (succeed or not)
Group Display Name
Target User

**Comment by reprise99** [comment]
Heya, something like this should work, just substitute in the days and user you want to investigate

let starttime = datetime(2022-11-21 00:00:00);
let endtime = datetime(2022-11-25 00:00:00);
let user = "user@domain.com";
AuditLogs
| where TimeGenerated between (starttime..endtime)
| where OperationName == "Add member to group"
| where Identity !in ("MS-PIM","Microsoft Approval Management")
| extend Actor = tostring(parse_json(tostring(InitiatedBy.user)).userPrincipalName)
| where Actor == (user)
| extend UserAdded = tostring(TargetResources[0].userPrincipalName)
| extend GroupName = tostring(parse_json(tostring(parse_json(tostring(TargetResources[0].modifiedProperties))[1].newValue)))
| project TimeGenerated, Result, Actor, UserAdded, GroupName
