### ISSUE TITLE
Sentinel-Queries/Office 365/OfficeActivity-NewTeamsAppInstalled.kql join type incorrect?

### ISSUE THREAD

**Issue by BeinGreen** [reprise99/Sentinel-Queries#2]
Ran the query against data in my environment, and the join type appears to be incorrect.  Should be rightsemi.

**Comment by reprise99** [comment]
What errors are you seeing when you run it in your tenant, or does the data just not look accurate? Rightanti should be the correct join, because first we look up all the apps installed over the past year (left), then return results from the last week that don't have a match (right).

**Comment by reprise99** [comment]
We talked about this on Twitter ages ago but I have just re-written this query, did you want to see if it now works? Instead of a join I am just using a let variable statement which is a bit more efficient. Should really be the same results but did you want to test?

**Comment by c016smith** [comment]
Thank you!!

**Comment by reprise99** [comment]
Awesome good to hear!
