### ISSUE TITLE
Query no longer works

### ISSUE THREAD

**Issue by cchambers-cap** [reprise99/Sentinel-Queries#26]
Query no longer runs because AADSpnSignInEventsBeta no longer exists (ErrorCode and Timestamp are also invalid)

https://github.com/reprise99/Sentinel-Queries/blob/211f6e959e5aecf1230c1810e2ee01a1e8ca706f/Azure%20Active%20Directory/Identity-ServicePrincipalswithSingleIP.kql#L27

**Comment by reprise99** [comment]
I just tested it in a lab tenant, and it is still ok, are you running that query in Advanced Hunting and not Sentinel? Unless those tables are slowly moving out of beta and your environment has migrated over already

**Comment by cchambers-cap** [comment]
I was running the query in Sentinel. I just tried it through Advanced Hunting  in the Security Portal and it works.

Looking at the results in Advanced Hunting, I think I saw the same results in Sentinel when I changed the query so that:
AADSpnSignInEventsBeta -> SigninLogs
Timestamp -> TimeGenerated
ApplicationId -> AppId
ErrorCode -> ResultType
IsManagedIdentity (can't remember what I used here)

If I go to connectors and search for "Service Principal sign-ins" I don't get any results (using an E5 license). Maybe we have migrated out of preview?
________________________________

**Comment by cchambers-cap** [comment]
Correction:
AADSpnSignInEventsBeta -> SigninLogs AADServicePrincipalSignInLogs
Timestamp -> TimeGenerated
ApplicationId -> AppId
ErrorCode -> ResultType
and remove the line:   | where IsManagedIdentity == 0

The query runs as expected and gives me the same results as I get in Advanced Hunting using the published query.

________________________________

**Comment by cchambers-cap** [comment]
Below is the full query I used in Sentinel to receive the same results as this one that worked in Security Portal -> Advanced Hunting

//Find Azure AD service principals that have only signed in from a single IP address in the last month. You should apply Conditional Access for workloads on them - https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/workload-identity

//Data connector required for this query - Azure Active Directory - Service Principal Signin Logs

//Microsoft Sentinel query
//First create a distinct count of IP addresses for each AppId and return any AppId with only 1 distinct IP
let appid=
    AADServicePrincipalSignInLogs
    | where TimeGenerated > ago (30d)
    | where ResultType == 0
    | summarize dcount(IPAddress) by AppId
    | where dcount_IPAddress == 1
    | distinct AppId;
//Query the same data for only those AppIds and summarize each IP by the AppId and friendly service principal names
AADServicePrincipalSignInLogs
| where TimeGenerated > ago (30d)
| where ResultType == 0
| where AppId in (appid)
| summarize ['Application Ids']=make_set(AppId) by IPAddress, ServicePrincipalName

//Advanced Hunting query

//Data connector required for this query - Advanced Hunting with Azure AD P2 License

//First create a distinct count of IP addresses for each AppId and return any AppId with only 1 distinct IP
let appid=
    AADServicePrincipalSignInLogs
    | where TimeGenerated > ago (30d)
    | where ResultType == 0
    | summarize dcount(IPAddress) by AppId
    | where dcount_IPAddress == 1
    | distinct AppId;
//Query the same data for only those AppIds and summarize each IP by the AppId and friendly service principal names
AADServicePrincipalSignInLogs
| where TimeGenerated > ago (30d)
| where ResultType == 0
| where AppId  in (appid)
| summarize ['Application Ids']=make_set(AppId) by IPAddress, ServicePrincipalName

________________________________

**Comment by cchambers-cap** [comment]
ok, I'm a total idiot (this is what I get for working on the weekends). Your git contains two queries, one for Sentinel and one for Advanced Hunting. I was putting both into Sentinel which caused it to use the Advanced Hunting one (blush)

Sorry!
________________________________

**Comment by reprise99** [comment]
All good! And yeah some I write both because the schema isn't a match (as you found out!)
